### ISSUE TITLE
how to compile the c++ code

### ISSUE THREAD

**Issue by zouweidong91** [google-research/pegasus#101]
Can you please give a example how to compile the c++ code in folder ops. For example where can I get the file 'strings/split.h' in rouge.cc line 29.  Thank you very much.

**Comment by zouweidong91** [comment]
@yaozhaogoogle Hi, I plan to train the chinese pre-training model, but there are some problems I can not fix it. I want to know how do you compile the c++ code in ops. I try to compile the c++ file in ops one by one using g++. However some file I can not find it,  for example 'util/hash/fingerprint2011.h', 'strings/split.h'  in rouge.cc . 
Which way do you use to compile the code, is cmake or bazel ? And can you please provide a example how to compile?  Thank you very much. 

This is my compile command for pretrain_parsing_ops.cc. And before this step I have compiled the abseil-cpp.
```
TF_CFLAGS=( $(python -c 'import tensorflow as tf; print(" ".join(tf.sysconfig.get_compile_flags()))') )
TF_LFLAGS=( $(python -c 'import tensorflow as tf; print(" ".join(tf.sysconfig.get_link_flags()))') )
export LD_LIBRARY_PATH=/usr/local/lib/python3.7/site-packages/tensorflow_core

g++ -std=c++11 -shared pegasus/ops/rouge.cc -o rouge.so -fPIC -labsl \
${TF_CFLAGS[@]} ${TF_LFLAGS[@]} -O2
```

**Comment by yuye2133** [comment]
同问中文版预训练步骤

**Comment by yaozhaogoogle** [comment]
@zouweidong91 strings/split.h is a part of ABSL. util/hash/fingerprint2011.h and 'Fingerprint2011' should be replaced with some hash function you have. We used Google's internal build system similar to bazel to compile the code. ABSL should cover all dependencies. Sorry I don't have examples as I haven't tried compiling this using cmake or blaze.
