### ISSUE TITLE
Implementing Transfer Learning using Pegasus for Text Summarization generating junk characters

### ISSUE THREAD

**Issue by anant-kumar-0308** [google-research/pegasus#109]
I've been trying to generate summaries following the steps as mentioned -
1. Created Input Data .tfrecord in pegasus\data\testdata
2. Created a function to return transformer_params named test_transformers (suppose)
3. Running ```python3 pegasus/bin/train.py  --params=test_transformer  --param_overrides=vocab_filename=ckpt/pegasus_ckpt/c4.unigram.newline.10pct.96000.model,batch_size=1,beam_size=5,beam_alpha=0.6 --model_dir=ckpt/pegasus_ckpt/xsum/model.ckpt-30000```
4. ```python3 pegasus/bin/evaluate.py  --params=test_transformer  --param_overrides=vocab_filename=ckpt/pegasus_ckpt/c4.unigram.newline.10pct.96000.model,batch_size=1,beam_size=5,beam_alpha=0.6  --model_dir=ckpt/pegasus_ckpt/xsum/model.ckpt-30000```

Code in ```public_params.py``` where ```save_path``` points to the ```testdata``` directory where tfrecord is stored which contains both ```inputs``` and ```targets```
```
@registry.register("test_transformer")
def test_transformer(param_overrides):
      return transformer_params(
              {
                  "train_pattern": save_path,
                  "dev_pattern": save_path,
                  "test_pattern": save_path,
                  "max_input_len": 1024,
                  "max_output_len": 256,
                  "train_steps": 100,
                  "learning_rate": 0.0001,
                  "batch_size": 10,
                  }, param_overrides)
```

However, I am getting junk characters when running this.

Is there some issue in the way its implemented or the way I'm running the python code in step 3 and 4?

Thanks in Advance !

**Comment by JingqingZ** [comment]
1. `--model_dir` is typically a directory instead of a particular checkpoint.
2. It seems there are only 100 training steps? `"train_steps": 100,`

**Comment by anant-kumar-0308** [comment]
Hey @JingqingZ , Thanks for the prompt reply. 

I've tried with the ```--model_dir``` set to ```ckpt/pegasus_ckpt/xsum```. 
Couldn't find any impact due to training and same results when using pretrained model was found (maybe because my ```train_steps``` was low). 

I have a few queries -
1. Does having same `train_pattern`, `dev_pattern` and `test_pattern` impact the training? - I'm using same tfrecord for all three purposes. I know these should be different but I've got a very small dataset of only 10k records.
2. What should be the minimum ```train_steps``` to reflect training ?
3. What should be the minimum requirement for GPU support ?
4. Does Pegasus work well with Dialogue Summarization task? - I've converted the flow of dialogues into paragraphs after certain cleansing steps and trying to summarize these dialogues. The results obtained were somewhat like - "Speaker_1 and Speaker_2's story", "Story of Speaker_1 and Speaker_2". I am not sure if Pegasus would serve the purpose. 

Thank you !

**Comment by JingqingZ** [comment]
1. No, but this also means you're testing on the training set.
2. You may check our paper appendix C for a rough idea of `train_steps`.
3. I tested NVIDIA TITAN X which worked fine. K80 should be ok too.
4. I would look forward to your results. I suppose PEGASUS should work well after fine-tuning on your dataset.

**Comment by anant-kumar-0308** [comment]
Thank you so much for the prompt response and support, will try with more ```train_steps``` and change ```model_dir``` to model directory rather than ```checkpoint``` !
