### ISSUE TITLE
Updating Security Measures

### ISSUE THREAD

**Issue by singhaditya28** [google-research/pegasus#11]
Dear Authors ,
Hope you're doing well 😃  !

I found out this project and immediately realised its potential. I want to update the project with some secure syntax. Can I get the names of the python files which are standalone and not being imported to other files so that I can create a dedicated PR ? Thanks in advance. 👍

PS :: I will try my best to make this project a success.

**Comment by JingqingZ** [comment]
Thanks! I didn't see the necessity for this at this moment.

**Comment by singhaditya28** [comment]
Are security measures not a necessity to one's project? How can you deny that? 😕

**Comment by jasonleschnik** [comment]
I can see you have gone through a lot of different high profile repros recently and updated the .gitignore files. This is fine, but I doubt this effort could scale. 

If you feel strongly about helping people keep gitignores secure and safe it would better serve your time to create a .gitignore analyser tool that implements best current practice for security. 

Just a thought.

**Comment by singhaditya28** [comment]
I'm on way on creating a website with a .gitignore creator 😄 You've guessed it right. But I want to update  all the files across github so that some **secret** info. is safe. Thus, I sincerely want to become a contributor to this project, even though small. 👍 😃 
Hope you understand.
