### ISSUE TITLE
Fine tuned (trained) on CNN but evaluating on my custom dataset

### ISSUE THREAD

**Issue by sadiayousafzai036** [google-research/pegasus#115]
Hi,

I have fine tuned pegasus on CNN dataset but I want to evaluate on my own custom dataset. How to do that?

**Comment by JingqingZ** [comment]
Hi this may help https://github.com/google-research/pegasus/issues/13#issuecomment-657167414

Or you may use the transformers by Huggingface: https://huggingface.co/models?filter=pegasus

**Comment by sadiayousafzai036** [comment]
Hi @JingqingZ ,
Thanks for your response. I checked the comment, unfortunately it just give prediction and does not create summarization metric files. Is there any other way to do so?

**Comment by JingqingZ** [comment]
The metric files should be created here: https://github.com/google-research/pegasus/blob/13fcf2b1191e0df950436c82c33d672c1447f5ff/pegasus/eval/text_eval.py#L129

**Comment by agenius5** [comment]
Hey, Can you please share you fine tuning code. I have trying but having some trouble.
