### ISSUE TITLE
How to fine-tune on limited number of samples?

### ISSUE THREAD

**Issue by agenius5** [google-research/pegasus#119]
Okay so I have 3 doubts. Please clarify.

So I manage to start the fine-tuning process on aescl dataset. Now I have 3 question regarding this process.

1) What does this mean?

I1026 10:11:43.616771 140123980212096 tpu_estimator.py:2307] global_step/sec: 0.368973
INFO:tensorflow:examples/sec: 2.95178
I1026 10:11:43.617043 140123980212096 tpu_estimator.py:2308] examples/sec: 2.95178
.....

2) The fine-tuning is going on full training data? In paper it is mentionied that fine-tuning can be done on limited number of example?

3) I don't see dataset getting download anywhere. So where the dataset is coming from? and if the dataset is getting download from tensorflow then how to fine-tune it with limited number of example?

**Comment by JingqingZ** [comment]
> 1. What does this mean?
> 
> I1026 10:11:43.616771 140123980212096 tpu_estimator.py:2307] global_step/sec: 0.368973
> INFO:tensorflow:examples/sec: 2.95178
> I1026 10:11:43.617043 140123980212096 tpu_estimator.py:2308] examples/sec: 2.95178

This shows the number of steps/examples that are processed each second.

> 2. The fine-tuning is going on full training data? In paper it is mentionied that fine-tuning can be done on limited number of example?

Please refer to the section 6.3 and figure 6 in the paper: https://arxiv.org/pdf/1912.08777.pdf

> 3. I don't see dataset getting download anywhere. So where the dataset is coming from? 

The dataset should be downloaded by tfds automatically so please refer to use guide of tfds. Some datasets require manual download such as xsum: https://www.tensorflow.org/datasets/catalog/xsum

> and if the dataset is getting download from tensorflow then how to fine-tune it with limited number of example?

https://github.com/google-research/pegasus/issues/50 can be helpful.
