### ISSUE TITLE
Further finetuning Pegasus using already fined tuned model

### ISSUE THREAD

**Issue by sadiayousafzai036** [google-research/pegasus#121]
Hi,

I have fine-tuned pegasus on CNN dataset. Now, I want to further fine-tune it on my dataset. I have specified the checkpoint that I got it from fine-tuning it on CNN dataset. However, I get the error below.

E1029 14:11:30.007478 140043760527168 error_handling.py:75] Error recorded from training_loop: Restoring from checkpoint failed. This is most likely due to a Variable name or other graph key that is missing from the checkpoint. Please ensure that you have not altered the graph expected based on the checkpoint. Original error:

Key decoder/LayerNorm/beta/Adafactor not found in checkpoint

**Comment by JingqingZ** [comment]
It seems the param `decoder/LayerNorm/beta/Adafactor` is missing in the checkpoint. I guess the checkpoint is the one you have finetuned on CNN? If so, it may be worth checking if the checkpoint was saved properly.

**Comment by agenius5** [comment]
Heyy, @sadiayousafzai036 I am also trying to fine-tune the model. Can you please tell me how much time it took you to fine-tune the model and where did you fine-tuned it. Also on how many examples you fine-tuned the model?

If you did it on colab, it'd be nice if you could share your colab to me perosnally.

**Comment by sadiayousafzai036** [comment]
Hi @agenius5,

It took me two days to fine-tune the model on CNN daily dataset. I used all examples.
I have HPC cluster on which I executed the training model.
