### ISSUE TITLE
Is it possible to break down the test sets, evaluate them and average out the results

### ISSUE THREAD

**Issue by agenius5** [google-research/pegasus#124]
So, I am evaluating on cnn_dailymail dataset on Colab and it is taking really long time, in total it'll take around 10-11 hours. So, if the colab decide to terminate my long session then I loose all the results. 

So, is it possible if I break down the test set into two parts (making tf records from tfds test split), evaluate seperately and then average the result of both the evaluation.

Also, three number are reported coresponding to each ROUGE measure. The middle one is the actual test result, I guess. What are the other two?

**Comment by JingqingZ** [comment]
You may save the generated summaries during testing and then compute rouge scores afterwards.

The three numbers in ROUGE are ROUGE-1F, ROUGE-2F, ROUGE-LF on test set.

**Comment by agenius5** [comment]
@JingqingZ  Thanks for your suggestions. 

> The three numbers in ROUGE are ROUGE-1F, ROUGE-2F, ROUGE-LF on test set.
I wanted to know what are the number corresponding to each ROUGE score. For example: there are three number in from of rouge1-F scores. The middle one is number test score I guess, what are the other two?

rouge1-R,0.331302,0.346532,0.361567
rouge1-P,0.394690,0.410827,0.428878
rouge1-F,### 0.333115,0.347364,0.361717

**Comment by JingqingZ** [comment]
https://github.com/google-research/pegasus/blob/13fcf2b1191e0df950436c82c33d672c1447f5ff/pegasus/eval/text_eval.py#L198

**Comment by agenius5** [comment]
@JingqingZ Okay! Thanks.
