### ISSUE TITLE
Extract Error on training

### ISSUE THREAD

**Issue by Papillon6814** [google-research/pegasus#133]
Hello.

```
tensorflow_datasets.core.download.extractor.ExtractError: Error while extracting /root/tensorflow_datasets/downloads/ucexport_download_id_1K2kDBTNXS2ikx9xKmi2_Lls0d7kG6NhLh-6Qt4tNUbCaluqBYTWYYmp4CluxakNVBI4 to /root/tensorflow_datasets/downloads/extracted/ZIP.ucexport_download_id_1K2kDBTNXS2ikx9xKmi2_Lls0d7kG6NhLh-6Qt4tNUbCaluqBYTWYYmp4CluxakNVBI4 (file: arxiv-release/train.txt) : Bad CRC-32 for file 'arxiv-release/train.txt'
```

I got this error on running train.py on google colaboratory. I remember I could run pegasus last week.
By the way, without changing the version of tensorflow-datasets, it throws an version error. So I have changed `requirements.txt` and `setup.py` with `tensorflow-datasets==1.3.1`.

How do you run pegasus?

**Comment by agenius5** [comment]
Try these:

!pip install tensorflow-datasets==3.0.0
!pip install tfds-nightly==3.1.0.dev202006230105

**Comment by Papillon6814** [comment]
@agenius5 
Thank you it worked!
