### ISSUE TITLE
Why the evaluation result changes each time I run the evaluation script (on same checkpoints)

### ISSUE THREAD

**Issue by agenius5** [google-research/pegasus#134]
My results my vary by some points each time I evaluate my trained model. I keep everything same but still results are off by .2 or .3. Why so?

**Comment by JingqingZ** [comment]
If training is True, the dropout layers may cause non-deterministic outcome. Decoding does some sampling as well but the sampling should be off by default.

**Comment by agenius5** [comment]
@JingqingZ Okay I didn't really understand what you said but I'll read about it. But, while evaluating Training should be false, right?
Anyways, those small differences shouldn't matter, right?

Also, I am trying to improve the results published in paper with a different training strategy. Right now I am working on AESLC dataset with only 1k examples. I need a little help from your side and if your interested then please let me know.

**Comment by JingqingZ** [comment]
Yes the `training` is false when evaluating. I suppose the minor difference shouldn't affect your expected conclusion.

I am afraid I won't be able to help you on the paper. Please let me know if you have any question about PEGASUS.

**Comment by agenius5** [comment]
@JingqingZ Okay, no problem. I'll ask whatever doubts I'll encounter related to PEGASUS here only. Your responses are really helpful so thanks a lot.
