### ISSUE TITLE
Building ops for pre-training

### ISSUE THREAD

**Issue by kalalopinska** [google-research/pegasus#135]
Hi,
I'm trying to build custom ops needed for pretrainig. I am following the tutorial: https://www.tensorflow.org/guide/create_op. 
My configuration is:
- ubuntu 16.04
- tensorflow source code version: 1.15.0, 1.15.2, 1.15.4 tested
- bazel version: 0.26.1
- gcc, g++ version: 7.3.0

bazel commands are:
`bazel build --config opt //tensorflow/core/user_ops:parsing_ops.so --cxxopt="-D_GLIBCXX_USE_CXX11_ABI=0"`
`bazel build --config opt //tensorflow/core/user_ops:pretrain_parsing_ops.so --cxxopt="-D_GLIBCXX_USE_CXX11_ABI=0"`

Error text: [error.txt](https://github.com/google-research/pegasus/files/5603675/error.txt)

Could I ask for some hint and used tool and tensorflow versions?
Thank you in advance

**Comment by JingqingZ** [comment]
@yaozhaogoogle Hi Yao, can you help on this issue? Thanks!

**Comment by kalalopinska** [comment]
The error is related to comparing int64 and uint64 types. They can be interpreted differently depending on the platform.  This is fixed in tf 2, the type test in the /tensorflow/core/framework/types.h file for the above-mentioned types is based on comparing their sizes.
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/framework/types.h#L402

**Comment by OpUs-Nebula** [comment]
Hello @JingqingZ, maybe you can answer this @kalalopinska: After building the ops, does calling
https://github.com/google-research/pegasus/blob/939830367bcf411193d2b5eca2f2f90f3f9260ca/pegasus/params/pegasus_params.py#L35
trigger pre-training? And then loading the model with

https://github.com/google-research/pegasus/blob/939830367bcf411193d2b5eca2f2f90f3f9260ca/pegasus/params/public_params.py#L28
for finetuning?

**Comment by JingqingZ** [comment]
Yes, that is correct.

**Comment by OpUs-Nebula** [comment]
Great, thanks!
