### ISSUE TITLE
Can I use any optimizer other than adafactor?

### ISSUE THREAD

**Issue by agenius5** [google-research/pegasus#143]
I see `multistep_optimizer` inside tensor2tensor library to simulate larger batch size but it uses adam optimzier. So is it possible to use it without affecting model's performance? Also why adam optimizer was choosed for PEGASUS? 

I don't much about these optimizers. Any insights will be helpful.

Thanks.

**Comment by JingqingZ** [comment]
Hi, we used Adafactor since it is more memory friendly than Adam.

**Comment by agenius5** [comment]
Okay how can i change it? Replacing adafactor with multistep_optimizer in `public_params.py` doesn't seems to be working. In logs I see adafactor only.

**Comment by JingqingZ** [comment]
You may change the optimizer: https://github.com/google-research/pegasus/blob/939830367bcf411193d2b5eca2f2f90f3f9260ca/pegasus/params/estimator_utils.py#L120

**Comment by agenius5** [comment]
Great. Thanks!!
