### ISSUE TITLE
In low resource setting results, does it matter which 1000 example I take from the dataset?

### ISSUE THREAD

**Issue by agenius5** [google-research/pegasus#150]
Hi, @JingqingZ

If I want to compare my results with low resource numbers reported in the papers (on any dataset), do I have to take same training examples that were used in the paper or any 1k/10k examples would be okay?

As per code, from the input pattern, `dataset.take(num_example)` method will take specified number of examples. I used the same method to take training examples and converted them to tfrecord with some changes. So, is that okay?

Also, if I take any 1000 examples then the results shouldn't vary much, right?

**Comment by JingqingZ** [comment]
We can't traceback the exact 100/1k/10k examples we used to finetune, so using the pattern `take_{num_sample}` would be the best path to proceed.

The more samples you use to finetune, the model should be more stable wrt to scores.

**Comment by agenius5** [comment]
Right, understood.
 
So basically, in this case we are just demonstrating model's ability to achieve good results when fine-tuned on limited examples, right?

**Comment by JingqingZ** [comment]
yes

**Comment by agenius5** [comment]
Thanks for the help as always.
