### ISSUE TITLE
Have you ever give a sentence to pegasus as you like?

### ISSUE THREAD

**Issue by Papillon6814** [google-research/pegasus#152]
Hello.
I'm using pegasus for my school work. I want to summarize any sentences with pegasus, but I don't know how.

Reading codes of pegasus, I guess I have to make a dataset of sentence at each summarization.

If you know any ways to do, please let me know🙇🙇🙇

**Comment by JingqingZ** [comment]
https://huggingface.co/transformers/model_doc/pegasus.html#usage-example

**Comment by Papillon6814** [comment]
Thank you!
