### ISSUE TITLE
Anyone prepared xsum dataset(manual) from tfds to work with pegasus

### ISSUE THREAD

**Issue by agenius5** [google-research/pegasus#153]
Hi,

I am facing issues when preparing xsum dataset as it requires running manual scripts to download more than 200k url's first. So, if anyone prepared the tar.gz which tfds uses to construct the dataset, please help! 

It'd be great if you can share that file.

Thanks!

**Comment by JingqingZ** [comment]
Hope this may help https://github.com/EdinburghNLP/XSum/issues/12

**Comment by agenius5** [comment]
Yep, it helped. 

Thanks!!!

**Comment by agenius5** [comment]
One more doubt.

I was able to prepare the dataset with some modification to `xsum.py` inside tensorflow_datasets and `tar.gz` downloaded from above mentioned link. 

So, here `target` is the TITLE and `inputs` is the RESTBODY field present in those bbc summary files (inside tar.gz file). Right? And we are not using the FIRST-SENTENCE field. The problem is, code in `xsum.py` took TITLE field as `targets` and FIRST-SENTENCE field as `inputs` which I think is wrong.

**Comment by agenius5** [comment]
One more doubt.

Summary files inside that `tar.gz` file contains four fields - URL, TITLE, FIRST-SENTENCE, RESTBODY. But, I was reading this code:

[https://github.com/EdinburghNLP/XSum/blob/master/XSum-Dataset/scripts/parse-bbc-html-data.py#L206](url)

I think after above prepocessing code remove the TITLE as well. 

Final dataset should contain RESTBODY as `inputs` and FIRST-SENTENCE as `targets`, is that right? If yes, I can make some changes to `xum.py` which is used to construct tfds to get my `inputs` and `target` correct.

**Comment by JingqingZ** [comment]
I think yes but I am not 100% sure. May worth checking https://www.tensorflow.org/datasets/catalog/xsum
