### ISSUE TITLE
Freeze encoder layers?

### ISSUE THREAD

**Issue by agenius5** [google-research/pegasus#157]
Hi, @JingqingZ 

My question is pretty vague but is it possible to freeze encoder layers and train the remaining? I am not sure how to do it as I first need to understand the transformer architecture and attention mechanism. But, can it be done with pegasus?

**Comment by JingqingZ** [comment]
Hi, you may need to check documentation of Tensorflow 1.15 to freeze part of the model.

**Comment by agenius5** [comment]
Hii, @JingqingZ 

I need a little guidance. I looked at the pegasus code closely and I suppose the enocder and decoder layers are defined here :

[https://github.com/google-research/pegasus/blob/master/pegasus/layers/transformer_block.py#L44](url)

and above code is called in a for loop from here:

[https://github.com/google-research/pegasus/blob/939830367bcf411193d2b5eca2f2f90f3f9260ca/pegasus/models/transformer.py#L52](url)

And what I did is set trainable=False like this `self._relu_layer = tf.layers.Dense(filter_size, activation=tf.nn.relu, Trainiable=False)` . But, there are three layers - attention, relu and output layer. 

Well, I'm not sure if my questions are correct. But, is it like those three layer(attention, relu and output) make up one enocder/decoder layer? And do i have to make all three non trainable to freeze them? 

It would be great you can give me some references and tell me if what I am thinking is correct or not.

**Comment by agenius5** [comment]
hey, @JingqingZ 

Okay. so I tried something. The encoder/decoder layer are defined here:

[https://github.com/google-research/pegasus/blob/master/pegasus/layers/transformer_block.py#L48](url)

and this is called from `transformer.py` to create encoder and decoder layers. So what I did is passed `trainable=False` like this - 
`self._output_layer = tf.layers.Dense(hidden_size, trainable=False)` to freeze some of the encoder layers. Now as I can see each encoder layer contains this 'relu_layer`, `output_layer` and `attention_layer`. So, do I need to freeze them all to freeze one encoder layer? 

Anyways, the bigger problem is this - 

Just for a experiment I freezed some encoder layer with `trainable=False`, started the fine-tunining and the training sucecessfuly started. But, the freezed layers parameters are somehow not getting saved. The `ckpt.index` and `ckpt.meta` file size are reduced then what it should be, although, checkpoint file is 2.1 gb only. The evaluation works fine but gives predicitions doesn't makes sense. Moreoever, when I try to resume training from these checkpoints without any freezed layer (everything set to normal), I get the following error - 

This is most likely due to a Variable name or other graph key that is missing from the checkpoint. Please ensure that you have not altered the graph expected based on the checkpoint.

Any references, guidance will be helpful.

**Comment by JingqingZ** [comment]
Hi, I am sorry I never tried to freeze part of the PEGASUS before. 

> So, do I need to freeze them all to freeze one encoder layer?

If you would like to freeze the whole encoder, then yes.

> But, the freezed layers parameters are somehow not getting saved. 

I can't see reasons given the description. You may need to debug your code.

**Comment by agenius5** [comment]
Okay! I'll look at it. 

Thanks!
