### ISSUE TITLE
Error" ModuleNotFoundError: No module named 'pegasus'

### ISSUE THREAD

**Issue by CBvanYperen** [google-research/pegasus#16]
Hi,

I would love to run this model in a Google Colab notebook. I tried following the README instructions but I ran into the following error:

```
Traceback (most recent call last):
  File "pegasus/bin/train.py", line 17, in <module>
    from pegasus.data import infeed
ModuleNotFoundError: No module named 'pegasus'
```

My notebook cells are as follows:
```
!git clone https://github.com/google-research/pegasus
```
```
%cd pegasus/
```
```
!export PYTHONPATH=.
!pip install -r requirements.txt
```

```
!sudo apt-get install gcc python-dev python-setuptools libffi-dev
!sudo apt-get install python-pip
!sudo pip install gsutil
```
```
!mkdir ckpt
!gsutil cp -r gs://pegasus_ckpt/ ckpt/
```
```
!python3 pegasus/bin/train.py --params=aeslc_transformer \
--param_overrides=vocab_filename=ckpt/pegasus_ckpt/c4.unigram.newline.10pct.96000.model \
--train_init_checkpoint=ckpt/pegasus_ckpt/model.ckpt-1500000 \
--model_dir=ckpt/pegasus_ckpt/aeslc
```

The last cell returns the error shown at the top of this message. I would appreciate  any help you could give me.

EDIT: Markdown

**Comment by kandarpkakkad** [comment]
Yes I think you need to install via 
<pre>
!pip3 install -e pegasus
</pre>
Keep in mind that you are outside the main pegasus folder.

**Comment by CBvanYperen** [comment]
Thanks, it worked perfectly!

**Comment by jayasridharmireddi** [comment]
> Hi,
> 
> I would love to run this model in a Google Colab notebook. I tried following the README instructions but I ran into the following error:
> 
> ```
> Traceback (most recent call last):
>   File "pegasus/bin/train.py", line 17, in <module>
>     from pegasus.data import infeed
> ModuleNotFoundError: No module named 'pegasus'
> ```
> 
> My notebook cells are as follows:
> 
> ```
> !git clone https://github.com/google-research/pegasus
> ```
> 
> ```
> %cd pegasus/
> ```
> 
> ```
> !export PYTHONPATH=.
> !pip install -r requirements.txt
> ```
> 
> ```
> !sudo apt-get install gcc python-dev python-setuptools libffi-dev
> !sudo apt-get install python-pip
> !sudo pip install gsutil
> ```
> 
> ```
> !mkdir ckpt
> !gsutil cp -r gs://pegasus_ckpt/ ckpt/
> ```
> 
> ```
> !python3 pegasus/bin/train.py --params=aeslc_transformer \
> --param_overrides=vocab_filename=ckpt/pegasus_ckpt/c4.unigram.newline.10pct.96000.model \
> --train_init_checkpoint=ckpt/pegasus_ckpt/model.ckpt-1500000 \
> --model_dir=ckpt/pegasus_ckpt/aeslc
> ```
> 
> The last cell returns the error shown at the top of this message. I would appreciate any help you could give me.
> 
> EDIT: Markdown

Hello, can you tell me what python, tensforflow versions you used?
