### ISSUE TITLE
How are important sentences to be masked selected

### ISSUE THREAD

**Issue by jiahao87** [google-research/pegasus#163]
Hi,

I was reading your [blog post](https://ai.googleblog.com/2020/06/pegasus-state-of-art-model-for.html) and trying to figure out from the example illustrated in the blog on how the two masked sentences are selected.

I noted that the sentences are selected based on the Rouge metric and so I calculated the ROUGE1-F1 (Ind-Orig) for each of the 4 sentences and obtained the following:
| Sentence      | ROUGE1-F1 |
| ----------- | ----------- |
| Pegasus is mythical      | 0.125       |
| It is pure white      | 0.25       |
| It names the model      | 0.125       |
| It is a cool name      | 0.25       |

Based on the ROUGE1-F1 score, the sentences with highest scores are "It is pure white" and "It  is a cool name". However they are not the ones that are masked.

Could I check if I am missing out something here? Why are the other two sentences "Pegasus is mythical" and "It names the model" masked instead?

**Comment by JingqingZ** [comment]
The gif is simply an illustration of masking gap sentences in general without referring to any particular masking strategy.

**Comment by jiahao87** [comment]
Oh ok, thank you for the clarification!
