### ISSUE TITLE
Missing comma in setup.py

### ISSUE THREAD

**Issue by CBvanYperen** [google-research/pegasus#17]
Hi,

I suspect that the requirements file in the setup.py is missing a comma. I'm not sure whether it is indeed the case as I read that others had gotten the model to work, but just in case I wanted to point it out. Hope it helps!

```
install_requires=[
        'absl-py',
        'mock',
        'numpy',
        'rouge-score',
        'sacrebleu',
        'sentencepiece',
        'tensorflow==1.15'         <-- I think there should be a comma here
        'tensorflow-text==1.15.0rc0',
        'tfds-nightly',
        'tensor2tensor==1.15.0',
    ],
```

EDIT: Markdown

**Comment by JingqingZ** [comment]
Thanks for catching this! Mixed by https://github.com/google-research/pegasus/pull/19
