### ISSUE TITLE
Problem install library and dependencies under Setup 

### ISSUE THREAD

**Issue by karimfayed** [google-research/pegasus#179]
### The following the error keeps popping  whenever i type in the command ' pip3 install -r requirements.txt '

*ERROR: Could not find a version that satisfies the requirement tensorflow-text==1.15.0rc0 (from -r requirements.txt (line 7)) (from versions: 2.4.0rc0, 2.4.0rc1, 2.4.1, 2.4.2, 2.4.3)*
*ERROR: No matching distribution found for tensorflow-text==1.15.0rc0 (from -r requirements.txt (line 7))*

**Comment by JingqingZ** [comment]
May try `pip install --upgrade pip`? Please note Tensorflow 1.15 does not support Python 3.8+ so you may need to downgrade your python version.

**Comment by karimfayed** [comment]
> May try `pip install --upgrade pip`? Please note Tensorflow 1.15 does not support Python 3.8+ so you may need to downgrade your python version.

Thank you! I upgraded the pip but still i was facing problems but it worked with this script for fine-tuning: https://gist.github.com/jiahao87/50cec29725824da7ff6dd9314b53c4b3
