### ISSUE TITLE
Is it possible to further train PEGASUS with the pretraining objective ? 

### ISSUE THREAD

**Issue by Skylixia** [google-research/pegasus#185]
Hi, 

I would be interested to load the pre-trained PEGASUS model and further train it with the GSG & MLM objective on a custom unlabeled dataset to only learn new embeddings. 
Is this possible? I see that to pretrain there is a small explanation in the README but I'm not sure it enables to do it from a checkpoint. 
Any indications on how to go about it ?

Thanks

**Comment by JingqingZ** [comment]
Technically, yes, you can continue pre-training the ckpts with GSG MLM further.
