### ISSUE TITLE
Rouge Metric

### ISSUE THREAD

**Issue by MartinEmilEshack** [google-research/pegasus#193]
I've been fine-tunning pegasus using the trainer class of huggingface.
I tried to implement the rouge metric using the [compute_metrics](https://github.com/huggingface/notebooks/blob/master/examples/summarization.ipynb) method _In [21]:_ but every time the following error happens

> TypeError: int() argument must be a string, a bytes-like object or a number, not 'list'

We are using the PegasusForConditionalGeneration transformers class
and according to [this post](https://discuss.huggingface.co/t/trainer-class-compute-metrics-and-evalprediction/1698/6) the predictions from the `eval_pred` parameter is a Tuple. Which I can't use to get the rouge scores.

**Is there anyway around this ?**

**Comment by JingqingZ** [comment]
Hi, we used https://github.com/google-research/google-research/tree/master/rouge
