### ISSUE TITLE
Plan to release large model

### ISSUE THREAD

**Issue by Huffon** [google-research/pegasus#2]
Hi authors
First of all, thank you for your awesome work!

I really enjoyed your paper with newly proposed GSP objective.
And I found your official implementation repository exists.

Just one question, do you guys plan to release large-sized model also?
I only found base model pre-trained on C4 datasets and am wondering if you have a plan to release large model.

Thanks,

**Comment by JingqingZ** [comment]
Hi, the model checkpoints provided on Google Cloud Bucket are large models (PEGASUS_LARGE). Thanks!

**Comment by Huffon** [comment]
Ah, didn't know that!
Thanks 😄
