### ISSUE TITLE
TypeError: load() got an unexpected keyword argument 'shuffle_files'

### ISSUE THREAD

**Issue by CBvanYperen** [google-research/pegasus#25]
Hi,

I am trying to get the model to work on a GCP Jupyter notebook. I chose the setting as closely as possible as in the README. That is,

- Environment: TensorFlow: 1.15
- Machine type: 8vCPUs, 52GB RAM (n1-highmem-8)
- GPU: NVIDIA Tesla V100 x 1
- Boot disk size: 500GB

I am running on python 3.7.6

Then I followed the rest of the README file as accurately as possible. Thus in the Jupyter notebook terminal:
```
git clone https://github.com/google-research/pegasus' (works fine)
cd pegasus
export PYTHONPATH=.
pip3 install -r requirements.txt
```
```
pip install -e pegasus' (This step is not in the README but in #16 )
```
Skipped the install gsutil step as it is installed by default
```
mkdir ckpt
gsutil cp -r gs://pegasus_ckpt/ ckpt/
```
Up until here everything seems to work perfectly.

The I run the finetuning command:
```
python3 pegasus/bin/train.py --params=aeslc_transformer \
--param_overrides=vocab_filename=ckpt/pegasus_ckpt/c4.unigram.newline.10pct.96000.model \
--train_init_checkpoint=ckpt/pegasus_ckpt/model.ckpt-1500000 \
--model_dir=ckpt/pegasus_ckpt/aeslc
```
And I receive the following error:
```
TypeError: load() got an unexpected keyword argument 'shuffle_files'
```

I tried running it through the terminal and through a jupyter notebook but both gave me the same error. Do you have any idea what might be causing this?

**Comment by JingqingZ** [comment]
What is your `pip freeze | grep tfds`?

My output: `tfds-nightly==3.0.0.dev202004160105` in case it is version problem of `tfds`.

**Comment by CBvanYperen** [comment]
I indeed had an older version of tdfs-nightly, running
```
pip3 install --upgrade tfds-nightly
```

resolved the problem. Thanks a lot for your help!
