### ISSUE TITLE
hi，will there be a docker soon？

### ISSUE THREAD

**Issue by BeHappyForMe** [google-research/pegasus#27]

**Comment by BeHappyForMe** [comment]
i have pull the tensorflow/tensorflow:1.15.2-gpu-py3-jupyter from docker hub,then i run the "pip3 install -r requirements.txt" but 
"
Collecting portalocker
	Downloading https://files.pythonhosted.org/packages/53/84/7b3146ec6378d28abc73ab484f09f47dfa008ad6f03f33d90a369f880e25/portalocker-1.7.0-py2.py3-none-any.whl
Collecting tensorflow<1.16,>=1.15.0
	Downloading https://files.pythonhosted.org/packages/02/36/9a02e27f0ec248b676a380ffe910c1858e3af3027c0d4d513dd0b56a5613/tensorflow-1.15.3-cp36-cp36m-manylinux2010_x86_64.whl (110.5MB)
", it seems install tensorlfow-1.15.3-cpu？。And my “tf.test.is_gpu_available” is false。I don`t know how to solve this，can anyone help me？

**Comment by BeHappyForMe** [comment]
I also try ”tensorflow/tensorflow:1.15.0-gpu-py3-jupyter”， before pip3 install -r requirements.txt， the  
“tf.test.is_gpu_available” is true, after it false.

**Comment by JingqingZ** [comment]
Hi, what does your `pip freeze | grep tensor` look like? 

Please check if https://github.com/google-research/pegasus/issues/12#issuecomment-640076157 can help and make sure `tensorflow-gpu` is installed at the last. It seems you installed `tensorflow-gpu` at the beginning.

**Comment by BeHappyForMe** [comment]
yes, i install the requirements.txt after tensorflow-gpu. But i tried as you say, it still didn`t worl.          pip freeze | grep tensor :  
root@ca55a25b5ddb:/tf/pegasus# pip freeze | grep tensor
mesh-tensorflow==0.1.13
tensor2tensor==1.15.0
tensorboard==1.15.0
tensorflow==1.15.3
tensorflow-datasets==3.1.0
tensorflow-estimator==1.15.1
tensorflow-gan==2.0.0
tensorflow-gpu==1.15.2
tensorflow-hub==0.8.0
tensorflow-metadata==0.22.2
tensorflow-probability==0.7.0
tensorflow-text==1.15.0rc0

**Comment by JingqingZ** [comment]
Hi, I notice you have different version of `tensorflow==1.15.3` and `tensorflow-gpu==1.15.2`. This is ok. But if the output of `python -c 'import tensorflow as tf; print(tf.__version__)' ` is `1.15.3`, then it means `python` actually imports the cpu version instead gpu version.

**Comment by BeHappyForMe** [comment]
Thank u，i have sloved it. Thank u again.
