### ISSUE TITLE
_registered_params is empty dict

### ISSUE THREAD

**Issue by amiyamandal-dev** [google-research/pegasus#28]
hello,
I was creating a prototype with a pre-trained model. But showing error when recreating the model using the steps given.

```
ValueError: Name 'aeslc_transformer' is not registered. Registered names are .
```
But when I am reading Source code and debugging it in
https://github.com/google-research/pegasus/blob/master/pegasus/params/registry.py
```
_registered_params = {}
```
This _registered_params is an empty dictionary.
So _registered_params has to be filled with any config that I am missing right now.

**Comment by JingqingZ** [comment]
The params are actually registered here: https://github.com/google-research/pegasus/blob/master/pegasus/params/public_params.py

Could you please provide instructions on how to replicate the error?

**Comment by dylangrosz** [comment]
Please reopen this issue. I'm also running into this issue. I see that _public_params.py_ registers _aeslc_transformer_ but it doesn't seem to carry over to _registry.py_?

**Comment by jayasridharmireddi** [comment]
> hello, I was creating a prototype with a pre-trained model. But showing error when recreating the model using the steps given.
> 
> ```
> ValueError: Name 'aeslc_transformer' is not registered. Registered names are .
> ```
> 
> But when I am reading Source code and debugging it in https://github.com/google-research/pegasus/blob/master/pegasus/params/registry.py
> 
> ```
> _registered_params = {}
> ```
> 
> This _registered_params is an empty dictionary. So _registered_params has to be filled with any config that I am missing right now.

Hello, did you get a solution for this?
