### ISSUE TITLE
Visualisation of the attention weight

### ISSUE THREAD

**Issue by kwtnb1111** [google-research/pegasus#3]
I have a question about the visualisation of the attention weight.
I’d like to visualise the weight in the self-attention layer.
So I extract the weight in inference with fine-tuned model for arxiv.
Could you show how to do that?

I realise that the `alignment_BxHxIxM`, which is in line 78 in attention.py, is weight.
However, I cannot extract it using fine-tuned model.

I would appreciate it if you could response me.

**Comment by JingqingZ** [comment]
Hi, you probably have to modify some code to get the attention weights. As far as I can see, you may need to pass the weight throughout the forward-feeding and return it as one of the outputs. At the same time, some changes to the estimator which is called by `bin/evaluate.py`.

**Comment by kwtnb1111** [comment]
Thank you so much for your response.
I modified the code and tried evaluating the fine-tuned model which you provided, but I have this error: ValueError: Could not find trained model in model_dir: arxiv (arxiv is the directory where we put the fine-tuned model).
If possible, could you please descrive how to use the fine-tuned model?
So sorry to bother you.
Thanks,

**Comment by JingqingZ** [comment]
I was running the fine-tuned model same as the instruction described in [README.md](https://github.com/google-research/pegasus#on-existing-dataset). Could you double-check if the trained model has been correctly located?

**Comment by kwtnb1111** [comment]
I checked that model.ckpt-340000.data-00000-of-00001, model.ckpt-340000.meta, and model.ckpt-340000.index, which were downloaded from `gs://pegasus_ckpt/` , are in the directory of arxiv, but it did not work. 

This directory of arxiv is in the same directory which contains setup.py, requirements.txt, and so on.
Is the place where we put them incorrect?

I observed the model I fine-tuned have worked with evaluation.py and this is the script used for the fine-tuned model which you gave: python3 pegasus/bin/evaluate.py --params=arxiv_transformer \
--param_overrides=vocab_filename=ckpt/c4.unigram.newline.10pct.96000.model,batch_size=1,beam_size=5,beam_alpha=0.6 \
--model_dir=arxiv

**Comment by JingqingZ** [comment]
Could you try to add a new file named `checkpoint` in the folder `arxiv` where the checkpoints are stored? In the `checkpoint` file, fill with

```
model_checkpoint_path: "model.ckpt-340000"
all_model_checkpoint_paths: "model.ckpt-340000"
```

**Comment by kwtnb1111** [comment]
It works!
Thank you so much for your advice.
