### ISSUE TITLE
Tensorflow custom ops: pretrain_parsing_ops

### ISSUE THREAD

**Issue by 6desislava6** [google-research/pegasus#32]
Hi there,
First, thank you for your wonderful work and sharing it to the outside world - it means a lot to many people!
I was wondering - If we want to change something in the pre-training, should we follow the official [Tensorflow's guide for adding an operation](https://www.tensorflow.org/guide/create_op): i.e. modifying pretrain_parsing_ops.cc and then building it again with bazel? According to the guide, we should also use `tf.load_op_library` to include the custom operation in python but I don't see that in the code. Maybe something else is happening e.g. creating a python wrapper?
Thanks in advance for the help!

**Comment by JingqingZ** [comment]
Hi, yes I would suggest following the Tensorflow's guide for ops as the code is in c++.

Actually, our README only provides instructions to run fine-tuning, which doesn't call any c++ code, so there is no need to load the c++ ops. The only ops that is used during fine-tuning is [ops/public_parsing_ops.py](https://github.com/google-research/pegasus/blob/master/pegasus/ops/public_parsing_ops.py), which has been refactored into python code.

**Comment by 6desislava6** [comment]
Thanks for the quick respond! I see...
So you suggest for pre-training to use the fine-tuning steps in the README?

**Comment by JingqingZ** [comment]
I mean if you would like to pre-train the model, you need to follow the Tensorflow's guide and build a customised tensorflow which includes the c++ ops.

The README steps are for the fine-tuning stage only, not pre-training.

**Comment by 6desislava6** [comment]
Thanks!
