### ISSUE TITLE
Fine-tuned Model

### ISSUE THREAD

**Issue by jiangix-paper** [google-research/pegasus#35]
Hello, Thanks a lot for your great works. I want to know the principle of fine-tuned model. For example, if i want to fine-tune the pretrained model on supervised cnn/dailymail dataset, is the model seq2seq? And i only load the pretrained word embedding based on pegasus, and set it as the input of seq2seq?

**Comment by JingqingZ** [comment]
> If i want to fine-tune the pretrained model on supervised cnn/dailymail dataset, is the model seq2seq? 

The model uses the encoder-decoder Transformer framework so yes it is seq2seq. 

> And i only load the pretrained word embedding based on pegasus, and set it as the input of seq2seq?

Sorry, I am not sure if I understand this question. Could you elaborate on your question?

**Comment by jiangix-paper** [comment]
> > If i want to fine-tune the pretrained model on supervised cnn/dailymail dataset, is the model seq2seq?
> 
> The model uses the encoder-decoder Transformer framework so yes it is seq2seq.
> 
> > And i only load the pretrained word embedding based on pegasus, and set it as the input of seq2seq?
> 
> Sorry, I am not sure if I understand this question. Could you elaborate on your question?

**Comment by jiangix-paper** [comment]
Thanks for your reply. When I fine-tune the model with encoder-decoder transformer framework on cnn/dailymail dataset,  whether the model structure and initial model parameter is the same as pretrained model. The model parameter of transformer encoder and decoder is updated during fine-tuning.

I want to sure whether the fine-tuned model are as follows:
![IMG_20200628_151058](https://user-images.githubusercontent.com/62198809/85940959-48ea6880-b952-11ea-8a93-12971ae19c9c.jpg)
