### ISSUE TITLE
Fine-tuned Model

### ISSUE THREAD

**Issue by jiangix-paper** [google-research/pegasus#37]
I'm sorry to close issue [#35 ](https://github.com/google-research/pegasus/issues/35) accidentally. 
So I continue my problem. When I fine-tune the model with encoder-decoder transformer framework on cnn/dailymail dataset, whether the model structure and initial model parameter is the same as pretrained model. The model parameter of transformer encoder and decoder is updated during fine-tuning.

I want to sure whether the fine-tuned model are as follows:
![issue](https://user-images.githubusercontent.com/62198809/85941579-59044700-b956-11ea-8e6f-649b74319af6.PNG)

**Comment by JingqingZ** [comment]
Yes, the fine-tuned model has exactly the same model structure as the pre-trained model. The fine-tuned model's parameters are initialized by the pre-trained model. Your picture looks correct.

**Comment by jiangix-paper** [comment]
OK, Thank you very much
