### ISSUE TITLE
ERROR "pip install -e pegasus"

### ISSUE THREAD

**Issue by jiangix-paper** [google-research/pegasus#40]
Hello, when I run the command "pip install -e pegasus", I got an error:

"ERROR: File "setup.py" not found. Directory cannot be installed in editable mode: ./pegasus-master/pegasus", I want to know how to fix it. Thanks a lot

**Comment by JingqingZ** [comment]
Hi maybe try to run `pip install -e pegasus` in the root directory which seems to be `./pegasus-master/` in your case.

**Comment by jiangix-paper** [comment]
Yes, it works. Thanks a lot
