### ISSUE TITLE
dynamic GSR confusing

### ISSUE THREAD

**Issue by Hayao41** [google-research/pegasus#49]
Hi, thx for great work about enhancing BERT like model's discourse and generation ability. I am reading the code of GSP sentence selecting & masking then I notice that the GSR for mixed & dynamic training is between 15% and 45%. 
```
- the model dynamically choose 15%-45% important sentences to generate
```
There are two points, which confused me a lot. 
### related code block
is the related code block as followed?
```
 } else if (strategy_ == "dynamic_rouge") {
      indices = GetSentenceIndicesByRouge(
          sentences_vec, text, rouge_,
          masked_sentence_ratio_ *
              absl::Uniform(gen, dynamic_mask_min_ratio_, 1.0),
          rouge_noise_ratio_);
...
```
### GSR setting
if it is, I noticed that the GSR setting here is sampled from Uniform(dynamic_mask_min_ratio_, 1.0), which is not matched with README's description.

**Comment by JingqingZ** [comment]
>  } else if (strategy_ == "dynamic_rouge") {
>       indices = GetSentenceIndicesByRouge(
>           sentences_vec, text, rouge_,
>           masked_sentence_ratio_ *
>               absl::Uniform(gen, dynamic_mask_min_ratio_, 1.0),
>           rouge_noise_ratio_);
> ...
> ```

Given the settings in [pegasus_params.py](https://github.com/google-research/pegasus/blob/13fcf2b1191e0df950436c82c33d672c1447f5ff/pegasus/params/pegasus_params.py), `parser_masked_sentence_ratio=0.45`, `parser_dynamic_mask_min_ratio=0.33` so the range is 15%-45%.

**Comment by Hayao41** [comment]
> > } else if (strategy_ == "dynamic_rouge") {
> > indices = GetSentenceIndicesByRouge(
> > sentences_vec, text, rouge_,
> > masked_sentence_ratio_ *
> > absl::Uniform(gen, dynamic_mask_min_ratio_, 1.0),
> > rouge_noise_ratio_);
> > ...
> 
> Given the settings in [pegasus_params.py](https://github.com/google-research/pegasus/blob/13fcf2b1191e0df950436c82c33d672c1447f5ff/pegasus/params/pegasus_params.py), `parser_masked_sentence_ratio=0.45`, `parser_dynamic_mask_min_ratio=0.33` so the range is 15%-45%.

Got it, thx a lot!
