### ISSUE TITLE
Difficulties to reproduce summarization results (CNNDM)

### ISSUE THREAD

**Issue by wonjininfo** [google-research/pegasus#5]
Hi, 
Thank you very much for sharing the checkpoints and the code. 
I am trying to reproduce the results of summarization datasets (CNNDM/XSum). 
For the CNNDM dataset, I used following command and got the result lower than the reported score. 
(I chooses the hyperparameter set from the paper (appendix-C))
```bash
python pegasus/bin/evaluate.py --params=cnn_dailymail_transformer \
> --param_overrides=vocab_filename=ckpt/pegasus_ckpt/c4.unigram.newline.10pct.96000.model,batch_size=1,beam_size=8,beam_alpha=0.8 \
> --model_dir=ckpt/pegasus_ckpt/cnn_dailymail/model.ckpt-210000 --evaluate_test
```
and got 
```
rouge1-R,0.458159,0.467907,0.477614
rouge1-P,0.432794,0.443048,0.451834
rouge1-F,0.431578,0.439820,0.447542
rouge2-R,0.218378,0.228153,0.238455
rouge2-P,0.207278,0.217396,0.227431
rouge2-F,0.205811,0.214875,0.224204
rougeL-R,0.322418,0.331526,0.341166
rougeL-P,0.304323,0.313319,0.322083
rougeL-F,0.302923,0.311144,0.319798
```

If I use 
```bash
param_overrides=vocab_filename=ckpt/pegasus_ckpt/c4.unigram.newline.10pct.96000.model,batch_size=1,beam_size=5,beam_alpha=0.6
```
I got slightly better score of `rougeL-F,0.304459,0.313382,0.321829`.

I guess I am missing some points. Also, I think I need to modify hyperparameters. 
Would you let me know the exact hyperparameters for evaluating CNNDM (and XSum) dataset?

**Comment by wonjininfo** [comment]
Sorry, my mistake.
I just found out from [here](https://github.com/google-research/google-research/tree/master/rouge) that `rougeLsum` is actually a summary-level ROUGE-L score.
`rougeLsum-F,0.397665,0.406826,0.415280`

Assuming from [here](https://github.com/google-research/pegasus/blob/13fcf2b1191e0df950436c82c33d672c1447f5ff/pegasus/eval/text_eval.py#L204), the second score looks matching with the reported score.
https://github.com/google-research/pegasus/blob/13fcf2b1191e0df950436c82c33d672c1447f5ff/pegasus/eval/text_eval.py#L204

Scores reproduced! Once again, my apologies for the misinterpretation. 
Best, 
Wonjin

**Comment by CBvanYperen** [comment]
Hi Wonjin, I am also trying to replicate the results in the paper. You say that you reproduced the scores, However, I cannot find the score that you posted anywhere in the paper. Could you please specify (with e.g. a screenshot) which score you have replicated with your code:
```
python pegasus/bin/evaluate.py --params=cnn_dailymail_transformer \
> --param_overrides=vocab_filename=ckpt/pegasus_ckpt/c4.unigram.newline.10pct.96000.model,batch_size=1,beam_size=8,beam_alpha=0.8 \
> --model_dir=ckpt/pegasus_ckpt/cnn_dailymail/model.ckpt-210000 --evaluate_test
```
