### ISSUE TITLE
Error when running evaluate.py: ImportError: cannot import name 'ContextManager' (Python 3.5)

### ISSUE THREAD

**Issue by yrutis** [google-research/pegasus#51]
I created an instance on google cloud according to your recommendation. When trying to evaluate on the finetuned dataset I get the following error:

`ImportError: cannot import name 'ContextManager'
`
Python 3.5 is installed. Which version is suggested?

**Comment by JingqingZ** [comment]
Hi, could you elaborate on the problem? Like the command you are using, traceback of the error, pip environment and packages' versions, etc.? I don't think our code uses `ContextManager` anywhere so I suspect it is not our code's problem.

**Comment by yrutis** [comment]
Thanks for the quick reply. 
Command: 
`python3 pegasus/bin/evaluate.py --params=aeslc_transformer \
> --param_overrides=vocab_filename=ckpt/pegasus_ckpt/c4.unigram.newline.10pct.96000.model,batch_size=1,beam_size=5,
beam_alpha=0.6 \
> --model_dir=ckpt/pegasus_ckpt/aeslc`

Traceback of the error:
`Traceback (most recent call last):
  File "pegasus/bin/evaluate.py", line 22, in <module>
    from pegasus.data import infeed
  File "/home/rutishauseryves/pegasus/pegasus/data/infeed.py", line 18, in <module>
    from pegasus.data import all_datasets
  File "/home/rutishauseryves/pegasus/pegasus/data/all_datasets.py", line 18, in <module>
    from pegasus.data import datasets
  File "/home/rutishauseryves/pegasus/pegasus/data/datasets.py", line 22, in <module>
    import tensorflow_datasets as tfds
  File "/home/rutishauseryves/.local/lib/python3.5/site-packages/tensorflow_datasets/__init__.py", line 47, in <mod
ule>
    from tensorflow_datasets.core import tf_compat
  File "/home/rutishauseryves/.local/lib/python3.5/site-packages/tensorflow_datasets/core/__init__.py", line 28, in
 <module>
    from tensorflow_datasets.core.dataset_builder import BeamBasedBuilder
  File "/home/rutishauseryves/.local/lib/python3.5/site-packages/tensorflow_datasets/core/dataset_builder.py", line
 36, in <module>
    from tensorflow_datasets.core import download
  File "/home/rutishauseryves/.local/lib/python3.5/site-packages/tensorflow_datasets/core/download/__init__.py", li
ne 20, in <module>
    from tensorflow_datasets.core.download.download_manager import DownloadConfig
  File "/home/rutishauseryves/.local/lib/python3.5/site-packages/tensorflow_datasets/core/download/download_manager
.py", line 37, in <module>
    from tensorflow_datasets.core.download import downloader
  File "/home/rutishauseryves/.local/lib/python3.5/site-packages/tensorflow_datasets/core/download/downloader.py", 
line 30, in <module>
    from typing import Any, ContextManager, Iterable, Iterator, Tuple, Union
ImportError: cannot import name 'ContextManager'`


Pip packages:
`
absl-py                  0.9.0                
appdirs                  1.4.3                
astor                    0.8.1                
attrs                    19.3.0               
backcall                 0.1.0                
bleach                   3.1.0                
bz2file                  0.98                 
cachetools               4.0.0                
certifi                  2019.11.28           
chardet                  3.0.4                
click                    7.1.2                
cloud-tpu-client         0.5                  
cloud-tpu-profiler       1.15.0rc1            
cloudpickle              1.5.0                
decorator                4.4.1                
defusedxml               0.6.0                
dill                     0.3.1.1              
distlib                  0.3.0                
distro                   1.0.1                
dopamine-rl              3.0.1                
entrypoints              0.3                  
filelock                 3.0.12
Flask                    1.1.2                
future                   0.18.2               
gast                     0.2.2                
gevent                   20.6.2               
gin-config               0.3.0                
google-api-python-client 1.7.11               
google-auth              1.11.2               
google-auth-httplib2     0.0.3                
google-compute-engine    20191210.0           
google-pasta             0.1.8                
googleapis-common-protos 1.51.0               
greenlet                 0.4.16               
grpcio                   1.27.2               
gunicorn                 20.0.4               
gym                      0.17.2               
h5py                     2.10.0               
httplib2                 0.17.0               
idna                     2.8                  
importlib-metadata       1.5.0                
importlib-resources      1.0.2                
ipykernel                5.1.4                
ipython                  7.9.0                
ipython-genutils         0.2.0                
ipywidgets               7.5.1                
itsdangerous             1.1.0                
jedi                     0.16.0               
Jinja2                   2.11.1               
joblib                   0.14.1               
jsonschema               3.2.0                
jupyter                  1.0.0                
jupyter-client           5.3.4                
jupyter-console          6.1.0                
jupyter-core             4.6.3                
Keras-Applications       1.0.8                
Keras-Preprocessing      1.1.0                
kfac                     0.2.0                
Markdown                 3.2.1                
MarkupSafe               1.1.1                
mecab-python3            0.996.5              
mesh-tensorflow          0.1.16               
mistune                  0.8.4                
mock                     3.0.5                
mpmath                   1.1.0
nbformat                 5.0.4                
nltk                     3.5                  
notebook                 6.0.3                
numpy                    1.18.1               
oauth2client             4.1.3                
opencv-python            4.3.0.36             
opt-einsum               3.1.0                
pandas                   0.25.3               
pandocfilters            1.4.2                
parso                    0.6.1                
pexpect                  4.8.0                
pickleshare              0.7.5                
Pillow                   7.2.0                
pip                      20.0.2               
portalocker              1.7.0                
prometheus-client        0.7.1                
promise                  2.3                  
prompt-toolkit           2.0.10               
protobuf                 3.11.3               
psutil                   5.7.0                
ptyprocess               0.6.0                
pyasn1                   0.4.8                
pyasn1-modules           0.2.8                
pycurl                   7.43.0               
pyglet                   1.5.0                
Pygments                 2.5.2                
pygobject                3.22.0               
pypng                    0.0.20               
pyrsistent               0.15.7               
python-apt               1.4.1                
python-dateutil          2.8.1                
pytz                     2020.1               
PyYAML                   5.3                  
pyzmq                    18.1.1               
qtconsole                4.6.0                
regex                    2020.6.8             
requests                 2.22.0               
rouge-score              0.0.4                
rsa                      4.0                  
sacrebleu                1.4.12 
scipy                    1.4.1                
Send2Trash               1.5.0                
sentencepiece            0.1.91               
setuptools               45.2.0               
six                      1.14.0               
sympy                    1.6.1                
tensor2tensor            1.15.0               
tensorboard              1.15.0               
tensorflow               1.15.0               
tensorflow-datasets      1.2.0                
tensorflow-estimator     1.15.1               
tensorflow-gan           2.0.0                
tensorflow-gpu           1.15.2               
tensorflow-hub           0.8.0                
tensorflow-metadata      0.21.1               
tensorflow-probability   0.7.0                
tensorflow-serving-api   1.14.0               
tensorflow-text          1.15.0rc0            
termcolor                1.1.0                
terminado                0.8.3                
testpath                 0.4.4                
tf-slim                  1.1.0                
tfds-nightly             3.1.0.dev202007070105
tornado                  6.0.3                
tqdm                     4.42.1               
traitlets                4.3.3                
unattended-upgrades      0.1                  
uritemplate              3.0.1                
urllib3                  1.25.8               
virtualenv               20.0.4               
wcwidth                  0.1.8                
webencodings             0.5.1                
Werkzeug                 1.0.0                
wheel                    0.34.2               
widgetsnbextension       3.5.1                
wrapt                    1.12.0               
zipp                     1.2.0                
zope.event               4.4                  
zope.interface           5.1.0                
`

**Comment by JingqingZ** [comment]
It seems problem in `tensorflow-datasets`. My `tensorflow-datasets==3.0.0` and python is 3.6.

**Comment by yrutis** [comment]
Hi, I was able to get it working on google colab and to get some predictions. Since they are quite extractive on scientific papers, I want to finetune it on arxiv where I need a better GPU than the one provided on colab (K80). On google cloud, the issue appears to be that python3.5 that is installed with the command provided:

`gcloud compute instances create \
  ${VM_NAME} \
  --zone=${ZONE} \
  --machine-type=n1-highmem-8 \
  --accelerator type=nvidia-tesla-v100,count=1 \
  --boot-disk-size=500GB \
  --image-project=ml-images \
  --image-family=tf-1-15 \
  --maintenance-policy TERMINATE --restart-on-failure`

upgrading it to python3.6 will hopefully work.

**Comment by yrutis** [comment]
After setting up the gcloud instance I ran into the same problem again. The problem was python 3.5 which can be seen in [this ](https://github.com/sdispater/cleo/issues/70)issue.
[Upgrading ](https://tecadmin.net/install-python-3-6-ubuntu-linuxmint/)to python3.6.10 solved the issue and then [upgrading ](https://stackoverflow.com/questions/59358265/how-to-install-tensorflow-1-15-0-in-ubuntu-server-18-04)pip3.6 before installing the dependencies

**Comment by tommydino93** [comment]
I had the same issue when running the [tf embedding example](https://www.tensorflow.org/tutorials/load_data/text).

Downgrading to tensorflow_datasets 3.0.0 solved the issue for me
