### ISSUE TITLE
Will BERT+transformer-decoder better than tensor2tensor for text-generation?

### ISSUE THREAD

**Issue by guotong1988** [google-research/pegasus#52]
Thank you very much.

**Comment by JingqingZ** [comment]
Hi, as we showed in [our paper](https://icml.cc/Conferences/2020/PosterSchedule#1219), our model outperformed BERTShare, which is an encoder-decoder framework from BERT. As far as I know, tensor2tensor is a library gathering different models and datasets. We didn't compare with implementation in tensor2tensor specifically. If you're referring to Transformer model by tensor2tensor, maybe you can check the results we reported in our paper on Transformer_Base model. Hope this answer your question.
