### ISSUE TITLE
successful prediction using evaluate.py but terminal hangs for 30 seconds before exiting to command prompt 

### ISSUE THREAD

**Issue by darienacosta** [google-research/pegasus#54]
Hi,

I was successful in using evaluate.py to generate expected output to "predictions-x.txt"
However I noticed that the script doesn't return to command line for another 30 seconds. The last log I see is  

error_handling.py:101] prediction_loop marked as finished 

And then it's an awkward 30 seconds to wait. Is this normal behavior? Is there anything I can do to eliminate the lag? Is this just the way TF works?

Thanks

**Comment by JingqingZ** [comment]
Hi, I think the program may need a few seconds to release resources. Given you have got the expected output, this should be fine.

**Comment by darienacosta** [comment]
Thanks. I think you're right. Even if I kill the script midprocess, it still takes some time to return to prompt.

**Comment by rohithsiddhartha** [comment]
Hey If I just pass a tf-record with one example with features inputs and targets. Evaluate execution has happened and then after finishing just text_metrics-2-.dev.txt file is created and the prediction and targets and inputs text file hasn't created. So, Ideally I can't view prediction generated by model if I just pass single example in tfrecord.

If I pass tf-record with 9 examples then it's using the whole 60gb ram from the instance and taking longer time for finishing the task.

Would like to explain why this is happening?
