### ISSUE TITLE
Is the cpp code related to the design of deep model?

### ISSUE THREAD

**Issue by guotong1988** [google-research/pegasus#56]
https://github.com/google-research/pegasus/tree/master/pegasus/ops

Based on my view, it seems the cpp code is about the data preprocess.

So if I want to learn the model, I do not need to care about the cpp code.

Am I right?

**Comment by JingqingZ** [comment]
The cpp code implements GSG's sentence selection strategies if you are interested in the pre-training objectives.

**Comment by guotong1988** [comment]
Thank you again.
