### ISSUE TITLE
testing trained model

### ISSUE THREAD

**Issue by PingYu-iris** [google-research/pegasus#57]
Hi there, 

I have trained pegasus on my own datasets. It received excellent results for the evaluation dataset. 

But right now, I don't know how to test on my test dataset. For example, my test dataset only have documents as inputs without labeled summaries. 

Thanks

**Comment by JingqingZ** [comment]
Hi, you may create some dummy targets to workaround.

**Comment by EKebriaei** [comment]
> Hi there,
> 
> I have trained pegasus on my own datasets. It received excellent results for the evaluation dataset.
> 
> But right now, I don't know how to test on my test dataset. For example, my test dataset only have documents as inputs without labeled summaries.
> 
> Thanks

Hi you, could you please help if you pretrained PEGASUS on your own dataset?
