### ISSUE TITLE
installation of gsutil

### ISSUE THREAD

**Issue by andifunke** [google-research/pegasus#6]
Hi,
thank you for this very interesting contribution!

There might be a small mistake in the documentation of the installation process.
`sudo apt install gsutil` installed the "GrandStream" manager on Ubuntu 20.04, but not google's gsutil.
However `pip install gsutil` worked for me. So maybe you just want to add it to the `requirements.txt` and remove the apt dependency from the documentation.

**Comment by JingqingZ** [comment]
Thanks for spotting this! The README has been updated accordingly. It is recommended to follow the installation instruction of `gsutil` on Google Cloud website as stated in the README now. As `gsutil` is not a dependency of PEGASUS code, it would be better to be installed separately.
