### ISSUE TITLE
Error while executing train command

### ISSUE THREAD

**Issue by sadiayousafzai036** [google-research/pegasus#67]
Hi,
I get the following error while executing command 
python3 pegasus/bin/train.py --params=aeslc_transformer \
--param_overrides=vocab_filename=ckpt/pegasus_ckpt/c4.unigram.newline.10pct.96000.model \
--train_init_checkpoint=ckpt/pegasus_ckpt/model.ckpt-1500000 \
--model_dir=ckpt/pegasus_ckpt/aeslc

Traceback (most recent call last):
  File "pegasus/bin/train.py", line 17, in <module>
    from pegasus.data import infeed
ModuleNotFoundError: No module named 'pegasus.data'

Although I do have pegasus folder with data folder in it and also the infeed python file.

**Comment by JingqingZ** [comment]
Hi, I am not quite sure what has happened in your local environment. Could you double-check if pegasus has been correctly installed following the README instruction? Some may mistakenly install another different pegasus on pip which is not ours.

**Comment by sadiayousafzai036** [comment]
Hi, 
Thankyou for your response. I have followed README instruction exactly for installation. I am using Ubuntu OS. Not sure why is this happening. I did it twice but still stuck at this point. For installing pegasus, is this the correct way?
pip3 install pegasus

**Comment by JingqingZ** [comment]
This is exactly what I was worried about. The command is incorrect. 

Please check README again and follow the instruction https://github.com/google-research/pegasus/#install-library-and-dependencies

You may need to `pip uninstall pegasus` first.

**Comment by sadiayousafzai036** [comment]
Hi,
Ah! I got it right now. By running requirements.txt file I get the following dependency error
Collecting tensorflow-gpu==1.15.2 (from -r requirements.txt (line 10))
  Could not find a version that satisfies the requirement tensorflow-gpu==1.15.2 (from -r requirements.txt (line 10)) (from versions: 0.12.1, 1.0.0, 1.0.1, 1.1.0, 1.2.0, 1.2.1, 1.3.0, 1.4.0, 1.4.1, 1.5.0, 1.5.1, 1.6.0, 1.7.0, 1.7.1, 1.8.0, 1.9.0, 1.10.0, 1.10.1, 1.11.0, 1.12.0, 1.12.2, 1.12.3, 1.13.1, 1.13.2, 1.14.0, 2.0.0a0, 2.0.0b0, 2.0.0b1)
No matching distribution found for tensorflow-gpu==1.15.2 (from -r requirements.txt (line 10))
I do not have GPU on my machine.

**Comment by JingqingZ** [comment]
upgrading your pip should fix

**Comment by sadiayousafzai036** [comment]
Thanks alot for your help. I was able to run Pegasus locally
