### ISSUE TITLE
 No matching distribution found for tensorflow-text==1.15.0rc0 - using pip latest

### ISSUE THREAD

**Issue by vedtam** [google-research/pegasus#72]
Hi,

I'm unable to install pegasus on OSX, using latest version of pip, it throws: 

```
ERROR: Could not find a version that satisfies the requirement tensorflow-text==1.15.0rc0 (from -r requirements.txt (line 7)) (from versions: 2.2.0, 2.2.1, 2.3.0rc1)
ERROR: No matching distribution found for tensorflow-text==1.15.0rc0 (from -r requirements.txt (line 7))
```

Tried to install it in a virtual env by downgrading pip to different versions, still no luck.

Could someone please help me out?
Thanks.

**Comment by JingqingZ** [comment]
I can install `tensorflow-text==1.15.0rc0` with `pip 20.1.1` and `python 3.6`

**Comment by vedtam** [comment]
hmm, thanks for the feedback, may have something to do that my python version is: 3.8.1. Trying to downgrade and try again. Brb.

**Comment by vedtam** [comment]
Managed to install python 3.6 and latest version of pip. Now I've got past the missing tensorflow-text distribution error but I got another error for:

`ERROR: No matching distribution found for tensorflow-gpu==1.15.2`

![Screen Shot 2020-07-21 at 14 00 31](https://user-images.githubusercontent.com/4981592/88047753-c4f35d00-cb5a-11ea-93c6-42986022c1b0.png)

**Comment by JingqingZ** [comment]
Hi, this looks novel to me. Could you refer to the official installation guide of tensorflow? `tensorflow-gpu` requires GPU and CUDA equipped in your computer. If GPU is not available on your mac, you may install `tensorflow==1.15.2` (CPU version) instead. Our code/model is still workable but will be slow.

**Comment by vedtam** [comment]
@JingqingZ thanks! Figured it out using the official TF install guide.

**Comment by medhini** [comment]
Hi, how did you go about resolving this issue?
