### ISSUE TITLE
Text preprocessing

### ISSUE THREAD

**Issue by nliu86** [google-research/pegasus#77]
Hi, I'm wondering what kind of text preprocessing I should use to get the maximum performance from the model.
For example, I have the following text:

How Fast Does It Go?
How fast a chemical reaction occurs is called the reaction rate. Several factors affect the rate of a given chemical reaction. They include the:

temperature of reactants.
concentration of reactants.
surface area of reactants.
presence of a catalyst.

Should I keep the line breakers to help model to understand the text better or the model doesn't care if the input is like this:
How Fast Does It Go? How fast a chemical reaction occurs is called the reaction rate. Several factors affect the rate of a given chemical reaction. They include the: temperature of reactants. concentration of reactants. surface area of reactants. presence of a catalyst.

How about casing, tokenization and sentence delineation? I noticed in arxiv's training data, they put a space between the sentence and the end-of-sentence period:
a prototype for many experimental systems that show hysteretic and jerky behavior when driven by an external force .

Should I do the same? Thanks!

**Comment by peterjliu** [comment]
Generally keep text as raw as possible including whitespace and casing.

**Comment by nliu86** [comment]
@peterjliu Thanks! how about the end-of-sentence period? If we just use the raw text, does the training or evaluation automatically know where the sentence ends?

**Comment by peterjliu** [comment]
Yep
