### ISSUE TITLE
Resource and time taken

### ISSUE THREAD

**Issue by rohithsiddhartha** [google-research/pegasus#78]
Hey If I just pass a tf-record with one example with features inputs and targets. Evaluate execution has happened and then after finishing just text_metrics-2-.dev.txt file is created and the prediction, targets and inputs text file isn't created. So, Ideally I can't view prediction generated by model if I just pass single example in tfrecord.

If I pass tf-record with 9 examples then it's using the whole 60gb ram from the instance and taking longer time for finishing the task.

Would like to explain why this is happening?

**Comment by JingqingZ** [comment]
Hi, could you provide more information on the command and code you ran? The creation of prediction, targets, inputs are implemented here https://github.com/google-research/pegasus/blob/13fcf2b1191e0df950436c82c33d672c1447f5ff/pegasus/eval/text_eval.py#L101.

It is normal the program will take more memory if a larger batch of data is fed into the model.

**Comment by rohithsiddhartha** [comment]
python3 evaluate.py --params=custom_transformer --param_overrides=vocab_filename=ckpt/c4.unigram.newline.10pct.96000.model,batch_size=1,beam_size=5,beam_alpha=0.6
--model_dir=/home/rohith/testing_ckpt

@registry.register("custom_transformer")
def custom_transformer(param_overrides):
  return transformer_params(
      {
          "train_pattern": "gs://pegasus_tf/custom/wikihow/all/1.2.0/wikihow-test.tfrecord-00000-of-00001",
          "dev_pattern":"/home/rohith/serving/pegasus/tf_record/single_feature.tfrecord",
          "test_pattern": "/home/rohith/serving/pegasus/tf_record/single_feature.tfrecord",
          "max_input_len": 1024,
          "max_output_len": 256,
          "train_steps": 100,
          "learning_rate": 0.0001,
          "batch_size": 8,
      }, param_overrides)

that single_feature.tfrecord has one example with features necessary.
I tried with different tfrecord which has 9-10 examples then it exhausted all the ram as I said in earlier comment.

Do you have any provision of smaller model which can be used instead of existing one which is being passed to vocab_filename. I tried to deploy model in AI-Platform after exporting the model using code from https://github.com/TheRockXu/pegasus-demo, it is running out of space even with the bigger machine type.

Do we have any alternate model which can be used to reduce the size of saved model or size of checkpoints created?

Error shown The total size of files in gs://pegasus_tf/saved_checkpoints/aa_pb_loading/savedmodel/1596031975/ is 2279874340 bytes, which exceeds the allowed maximum of 2097152000 bytes.

**Comment by JingqingZ** [comment]
I am very sorry I can't identify the error. We have tested the model is runnable on single TITAN X GPU. We're not able to release small models due to incompatibility issue.

**Comment by rohithsiddhartha** [comment]
> I am very sorry I can't identify the error. We have tested the model is runnable on single TITAN X GPU. We're not able to release small models due to incompatibility issue.

Okay.
Can you tell what could be the reason for text files not being created after successfully completing the execution with out any error shown in the logs when a tf record with single example is passed?
When tfrecord with multiple examples is passed, evaluation is being done and text files are also created. Can you try to replicate the issue by using a tfrecord with single example and let me know whether text are created or not.

**Comment by chetanambi** [comment]
@rohithsiddhartha I am able to generate both extractive and abstractive summary successfully with single example. If you can elaborate the steps you followed I will try to help you out.

**Comment by rohithsiddhartha** [comment]
> @rohithsiddhartha I am able to generate both extractive and abstractive summary successfully with single example. If you can elaborate the steps you followed I will try to help you out.

I have ran it as mentioned in the official repo, the changes that I made are instead of looking for features of inputs and targets I changed it to description and abstract. Replaced every other code which uses feature inputs to description and target to abstract. 
That's the only change that I made and tested the code, Training is completed successfully and for evaluation on tfrecord with multliple examples is also successful in AI platform by using TPU.

Here the code which is executed on AI platform after launching the job. Text files are created if I pass tf records with multiple examples on AI paltform.

When I passed single example or evaluation on instance (not TPU just ram based GPU) it didn't create text files necessary. 


model_dir has the checkpoints which are created when training job is launched on custom dataset, using fine-tuned checkpoint of big patent(model.ckpt-480000) as train_init_checkpoint while passing arguments for training job, which is provided in the link from which we usually download all the necessary checkpoints/model files provided by collaborators.

Training job inputs
"--params=custom_transformer",
    "--param_overrides=vocab_filename=gs://pegasus_tf/pegasus_ckpt/c4.unigram.newline.10pct.96000.model,batch_size=1,train_steps=100,learning_rate=0.0001",
    "--train_init_checkpoint=gs://pegasus_tf/pegasus_ckpt/big_patent/model.ckpt-480000",
    "--model_dir=gs://pegasus_tf/saved_checkpoints/aa_pb_loading",

Evaluation job inputs are provided in the above comments. Model directory path provided in evaluation is different as I downloaded the content from bucket and used them in instance. 

Can you be descriptive on how you generated both abstractive and extractive summarization. Is it just on the basis of training dataset or any other major changes that you did to extract both?

Did you do any major changes in the code to evaluate on tfrecord with single example, if yes let me know.

**Comment by chetanambi** [comment]
@rohithsiddhartha  This is the code I am using to generate summaries and it;s working perfectly fine. I hope you find this useful. Please let me know if any questions.

```
!git clone https://github.com/google-research/pegasus
%cd pegasus
!export PYTHONPATH=.

!pip3 install -r requirements.txt

!sudo apt-get install gcc python-dev python-setuptools libffi-dev

!sudo apt-get install python-pip

!sudo pip install gsutil

!mkdir ckpt
!gsutil cp -r gs://pegasus_ckpt ckpt/

%cd ..

!pip3 install -e pegasus

%cd /content/pegasus/

import pandas as pd
import tensorflow as tf

input_dict = dict(
    inputs=[inp],
    targets=[""]
    )

save_path = "pegasus/data/testdata/test_pattern_1.tfrecord"
data = pd.DataFrame(input_dict)
with tf.io.TFRecordWriter(save_path) as writer:
    for row in data.values:
        inputs, targets = row[:-1], row[-1]
        example = tf.train.Example(
            features=tf.train.Features(
                feature={
                    "inputs": tf.train.Feature(bytes_list=tf.train.BytesList(value=[inputs[0].encode('utf-8')])),
                    "targets": tf.train.Feature(bytes_list=tf.train.BytesList(value=[targets.encode('utf-8')])),
                }
            )
        )
        writer.write(example.SerializeToString())

start = time.perf_counter()

!python3 pegasus/bin/evaluate.py \
--params=reddit_tifu_long_transformer \
--param_overrides=vocab_filename=ckpt/pegasus_ckpt/c4.unigram.newline.10pct.96000.model,batch_size=1,beam_size=5,beam_alpha=0.6 \
--model_dir=ckpt/pegasus_ckpt/reddit_tifu/model.ckpt-8000

end = time.perf_counter()
print('\nTotal time take for prediction (in mins):', (end-start)/60)
```

Before running this evaluation step I am updating public_params.py for the downstream dataset of my interest (in this case I am interested in reddit_tifu)

```
save_path = "tfrecord:/content/pegasus/pegasus/data/testdata/test_pattern_1.tfrecord"
@registry.register("reddit_tifu_long_transformer")
def reddit_tifu_long_transformer(param_overrides):
  return transformer_params(
      {
          "train_pattern": save_path,  
          "dev_pattern": save_path,  
          "test_pattern": save_path, 
          "max_input_len": 1024,
          "max_output_len": 128,
          "train_steps": 8000,
          "learning_rate": 0.0001,
          "batch_size": 8,
      }, param_overrides)
```

**Comment by rohithsiddhartha** [comment]
@chetanambi Thanks, iI worked actually. I might have done some major changes in the code. I'll have to look at it or else just make the changes in the source itself.

Can you be tel on how you generated both abstractive and extractive summarization. Is it just on the basis of training dataset or any other major changes that you did to extract both? 

In PEGASUS, what I got to know after going through other issues is that it does both extractice and abstractive summarization but it highly depends on the format of training dataset. Pegasus has provided checkpoints for multiple datasets/down streaming tasks ( XSum, CNN/Daily mail, NEWSROOM, Multinews, Gigaword, arxiv, bigpatent, wikihow, reddit tifu, aeslc and billsum)

If you are aware on what all are abstractive and extractive datasets. It would be helpful.

@JingqingZ I think you'll be able to comment on detail which dataset can be used for extractive and which one abstractive summarization. 

Thanks in Advance

**Comment by chetanambi** [comment]
@rohithsiddhartha Yes, extractice and abstractive summarization depends on the downstream dataset used. Please refer Summarization section here https://www.tensorflow.org/datasets/catalog/  Whether the particular downstream dataset is abstractive or extractive is mentioned here.

**Comment by JingqingZ** [comment]
That's right! We reported some analysis on the abstractiveness and extractiveness of the downstream datasets and the models fine-tuned on them in the Appendix A and H of [our paper](https://arxiv.org/pdf/1912.08777.pdf).
