### ISSUE TITLE
The CPP code is the faster way to prepare pretrain data?

### ISSUE THREAD

**Issue by guotong1988** [google-research/pegasus#82]
https://github.com/google-research/pegasus/tree/master/pegasus/ops

The CPP code is much faster than Python code. Am I right?
So the CPP code can be coded to the format of my own?
Thank you very much!
@JingqingZ

**Comment by JingqingZ** [comment]
Hi, we didn't test the speed of Python vs. C++ for this particular case. The code here was mostly written in C++ for the ease of development of text preprocessing in TF1.

What is "the format of my own"?

**Comment by guotong1988** [comment]
If the speed of cpp is faster, then I can use it for data preparing for pretrain task like BERT.
