### ISSUE TITLE
How to compile the CPP code in my own linux machine?

### ISSUE THREAD

**Issue by guotong1988** [google-research/pegasus#83]
https://github.com/google-research/pegasus/tree/master/pegasus/ops

Thank you very much!
@JingqingZ

**Comment by guotong1988** [comment]
The whole doc from https://github.com/google/clif seems too long..

**Comment by JingqingZ** [comment]
I am not sure if there is a quick start. How about this https://www.tensorflow.org/guide/create_op?

**Comment by zouweidong91** [comment]
> The whole doc from https://github.com/google/clif seems too long..
> 
> Is there any quick-start doc?

Do you have any idea about how to compile the cpp code? I am very interested.
