### ISSUE TITLE
ValueError: ("Checkpoints ckpt/pegasus_ckpt/ doesn't exist ", "and evaluation doesn't wait.")

### ISSUE THREAD

**Issue by shiveshchoudhary** [google-research/pegasus#85]
I was trying to run the pretrained model for customized textual data by following this [link](https://medium.com/thecyphy/generating-abstractive-summaries-using-googles-pegasus-model-18eef8ae985b) and on using the command 
`python3 pegasus/bin/evaluate.py --params=test_transformer \
--param_overrides=vocab_filename=ckpt/pegasus_ckpt/c4.unigram.newline.10pct.96000.model,batch_size=1,beam_size=5,beam_alpha=0.6 \
--model_dir=ckpt/pegasus_ckpt/`
and ran into following error.

Error log
` WARNING:tensorflow:From pegasus/bin/evaluate.py:152: The name tf.enable_eager_execution is deprecated. Please use tf.compat.v1.enable_eager_execution instead.

WARNING:tensorflow:From pegasus/bin/evaluate.py:153: The name tf.app.run is deprecated. Please use tf.compat.v1.app.run instead.

WARNING:tensorflow:From pegasus/bin/evaluate.py:85: checkpoint_exists (from tensorflow.python.training.checkpoint_management) is deprecated and will be removed in a future version.
Instructions for updating:
Use standard file APIs to check for files with this prefix.
W0811 15:00:54.445491 140183829018432 deprecation.py:323] From pegasus/bin/evaluate.py:85: checkpoint_exists (from tensorflow.python.training.checkpoint_management) is deprecated and will be removed in a future version.
Instructions for updating:
Use standard file APIs to check for files with this prefix.
Traceback (most recent call last):
  File "pegasus/bin/evaluate.py", line 153, in <module>
    tf.app.run(main)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/platform/app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "/usr/local/lib/python3.6/dist-packages/absl/app.py", line 299, in run
    _run_main(main, args)
  File "/usr/local/lib/python3.6/dist-packages/absl/app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "pegasus/bin/evaluate.py", line 87, in main
    "and evaluation doesn't wait."))
**ValueError: ("Checkpoints ckpt/pegasus_ckpt/ doesn't exist ", "and evaluation doesn't wait.")** `

While both ckpt and pegasus_ckpt exists in my env at their respective locations

**Creation of input data Code**

` import pandas as pd
import tensorflow as tf

save_path = "shivesh/pegasus/data/testdata/test_pattern_1.tfrecords"

input_dict = dict(
                  inputs=[
                          "While most animals with feline infectious peritonitis don’t show symptoms, some cats can develop severe illness if the virus mutates to infect a specific type of immune cell. When that happens, the coronavirus spreads throughout the cat’s body, sparking a deadly inflammatory reaction that can cause paralysis or fluid to accumulate in the lungs."
                         ],
                  targets=[
                          ""
                          ]
                 )

data = pd.DataFrame(input_dict)

with tf.io.TFRecordWriter(save_path) as writer:
    for row in data.values:
        inputs, targets = row[:-1], row[-1]
        example = tf.train.Example(
            features=tf.train.Features(
                feature={
                    "inputs": tf.train.Feature(bytes_list=tf.train.BytesList(value=[inputs[0].encode('utf-8')])),
                    "targets": tf.train.Feature(bytes_list=tf.train.BytesList(value=[targets.encode('utf-8')])),
                }
            )
        )
        writer.write(example.SerializeToString()) `

**Addition of code at the end of public_params.py**

save_path = "shivesh/pegasus/data/testdata/test_pattern_1.tfrecords"
@registry.register("test_transformer")
def test_transformer(param_overrides):
  return transformer_params(
      {
          "train_pattern": save_path,
          "dev_pattern": save_path,
          "test_pattern": save_path,
          "max_input_len": 1024,
          "max_output_len": 256,
          "train_steps": 180000,
          "learning_rate": 0.0001,
          "batch_size": 8,
      }, param_overrides)

**Comment by JingqingZ** [comment]
> ValueError: ("Checkpoints ckpt/pegasus_ckpt/ doesn't exist ", "and evaluation doesn't wait.") `

How about this solution: https://github.com/google-research/pegasus/issues/3#issuecomment-634034845? You can create a similar `checkpoint` file in `ckpt/pegasus_ckpt/`.

**Comment by chetanambi** [comment]
@shiveshchoudhary Please check [this](https://towardsdatascience.com/generate-summaries-using-googles-pegasus-library-772633a161c2?source=friends_link&sk=34f770a509abdb972e905c9222bc3a29). After the initial trouble I was able to run Pegasus successfully.

**Comment by vojsa5** [comment]
Have the same problem, creating checkpoint does not solve it for me.

**Comment by mattfast** [comment]
@shiveshchoudhary Were you ever able to resolve above issue? I am running into same issue currently.
