### ISSUE TITLE
abstract of an arbitrary text

### ISSUE THREAD

**Issue by Dmitriuso** [google-research/pegasus#87]
Hey guys,
I was looking for a possibility to test PEGASUS on an arbitrary text, is there already a way to do so? After fine-tuning, of course. 
Thanks in advance.

**Comment by JingqingZ** [comment]
Hi, hope this may help https://github.com/google-research/pegasus/issues/13#issuecomment-657167414 or you can use the implementation by Huggingface https://huggingface.co/models?filter=pegasus.

**Comment by Dmitriuso** [comment]
@JingqingZ  Thanks a lot!
