### ISSUE TITLE
Input length greater than 1024

### ISSUE THREAD

**Issue by Asayesha** [google-research/pegasus#88]
Hi, 

I am trying to understand if I can have input lengths greater than 1024. Can I set the pubmed max_input_length >1024 (in public_params) and then fine tune the model on pubmed data ? 
Currently the the max_input_length for pubmed is 1024.

I ask because I am trying to understand the 2nd line in the following paragraph from the paper :

"CNN/DailyMail, Multi-News, arXiv, PubMed, BIGPATENT datasets contain input documents longer than
the maximum input length (Linput = 512 tokens) in pretraining. This would present a problem for position embeddings which would never be updated for longer input
lengths, but we confirm the postulation that sinusoidal positional encodings (Vaswani et al., 2017) generalize well
when fine-tuning PEGASUSLARGE beyond the input lengths
observed in training up to Linput = 1024 tokens."

Any inputs on this would be of great help. Thanks in advance!

**Comment by JingqingZ** [comment]
Hi, in theory, you can use an input text with > 1024 tokens but it will lead to huge memory cost in the self-attention, as explained by this [paper](https://arxiv.org/abs/2007.14062).

Position embedding learns embeddings for absolute positions like 1st, 2nd, 3rd tokens. But sinusoidal positional encodings encodes relative positions of tokens e.g. the relative positions between i-th and j-th tokens.

**Comment by Asayesha** [comment]
Thank you for your prompt response @JingqingZ. 
I want to use the pubmed model. So, if for a moment if we keep the memory cost aside, if I have inputs lengths > 1024 for medical text, what changes will I have to make ?  Will I have to fine-tune it again or can I still directly use the published fine-tuned model of pubmed?  Please let me know.

Also, can pegasus be used for multi document summarization ? If yes, could you please let me know what changes are needed.

**Comment by JingqingZ** [comment]
You may need to change the `max_input_len` in https://github.com/google-research/pegasus/blob/master/pegasus/params/public_params.py

From my perspective, fine-tuning it again should be helpful.

PEGASUS is designed for single-document summarization. If you have multiple input documents, potential solutions may include (1) concatenating the documents together and feed it into the model, which will only take the first `max_input_len` tokens, (2) extract most informative segments and concatenate them as one document.

**Comment by Asayesha** [comment]
Thank you. I am closing this issue.

**Comment by Asayesha** [comment]
Hi, I just have another question.
On similar lines, can we increase the max_output_length in public_params ? Will increasing it lead to any problems (like memory cost or anything else) ?

**Comment by JingqingZ** [comment]
Increasing `max_output_len` will also lead to larger memory cost.

**Comment by Asayesha** [comment]
Thank you for your prompt response.
