### ISSUE TITLE
mixed+stochastic fine-tuning results

### ISSUE THREAD

**Issue by jacob-parnell-rozetta** [google-research/pegasus#91]
Hi, in Section 6.3 of your paper, you mention that PEGASUS is pre-trained on HugeNews and is then fine-tuned on a number of datasets, and shown to have great low resource summarisation results.

Do you at all have any low-resource fine-tuning results (as reported in Section 6.3) using the mixed+stochastic PEGASUS(LARGE) model, or are the added results in Section 6.6, purely fine-tuned on all examples for each dataset?

**Comment by JingqingZ** [comment]
Sorry, we didn't run low-resource using mixed+stochastic.
