### ISSUE TITLE
Pretrain for other languages

### ISSUE THREAD

**Issue by Ian-Jung** [google-research/pegasus#99]
Hello. I'm very interested in your research.
I try to pretrain pegasus on other languages but it didn't train well.
When my trained model predicted, It only produced token <">.

Can you provide any guide?

**Comment by JingqingZ** [comment]
Hi, can provide more information on how you pretrain?

**Comment by kalalopinska** [comment]
@Ian-Jung 
Hello, 
Could you provide tools and tensorflow versions?

**Comment by leewonmin** [comment]
안녕하세요, 사전 교육 방법에 대한 자세한 정보를 제공 할 수 있습니까?

**Comment by Ian-Jung** [comment]
안녕하세요. 내부적으로 검토한 결과 사전 훈련에 쓰인 말뭉치의 크기가 충분하지 않아 발생한 문제라고 결론을 맺었습니다. 현재는 말뭉치를 추가로 확보하고 있으며, 다른 사전 학습 모델을 사용하고 있습니다.

**Comment by Ian-Jung** [comment]
> @Ian-Jung
> Hello,
> Could you provide tools and tensorflow versions?

Hello. I and my co-workers reviewed this issue, and we concluded that the problem was caused by an insufficient size of the corpus used for pre-training. We experienced similar problems in other task, that's why we stopped pretraining. Thanks.
